### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by pehbeh** [wbbaddons/Faker#7]
Warning: Uncaught exception 'wcf\system\exception\SystemException' with message 'PHP warning in file /Applications/XAMPP/xamppfiles/htdocs/wcf2/wcf/lib/system/worker/FakerWorker.class.php (62): require_once(/Applications/XAMPP/xamppfiles/htdocs/wcf2/wcf/lib/system/api/faker/src/autoload.php): failed to open stream: No such file or directory' in /Applications/XAMPP/xamppfiles/htdocs/wcf2/wcf/lib/system/WCF.class.php:288 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/wcf2/wcf/lib/system/worker/FakerWorker.class.php(62): wcf\system\WCF::handleError(2, 'require_once(/A...', '/Applications/X...', 62, Array) #1 /Applications/XAMPP/xamppfiles/htdocs/wcf2/wcf/lib/system/worker/FakerWorker.class.php(62): wcf\system\worker\FakerWorker::execute() #2 /Applications/XAMPP/xamppfiles/htdocs/wcf2/wcf/lib/acp/action/WorkerProxyAction.class.php(88): wcf\system\worker\FakerWorker->execute() #3 /Applications/XAMPP/xamppfiles/htdocs/wcf2/wcf/lib/action/AbstractAction.class.php(49): wcf\acp\action\WorkerProxyAction->execute() #4 /Ap in /Applications/XAMPP/xamppfiles/htdocs/wcf2/wcf/lib/system/WCF.class.php on line 288

Fatal error: wcf\system\worker\FakerWorker::execute(): Failed opening required '/Applications/XAMPP/xamppfiles/htdocs/wcf2/wcf/lib/system/api/faker/src/autoload.php' (include_path='.:/Applications/XAMPP/xamppfiles/lib/php') in /Applications/XAMPP/xamppfiles/htdocs/wcf2/wcf/lib/system/worker/FakerWorker.class.php on line 62

**Comment by TimWolla** [comment]
You probably forgot to include the submodule into your package.

**Comment by pehbeh** [comment]
Argh…sorry!
